### ISSUE TITLE
Missing libraries

### ISSUE THREAD

**Issue by paolosanchi** [gretel/MIDIsync#2]
Hello,
the two libraries "movingAvg" and "Button" are missing, I can't find the compatible ones on internet.
Which i found causes  some errors:
https://github.com/tigoe/Button
https://github.com/JChristensen/movingAvg

**Comment by gretel** [comment]
doh sorry, going to add them.

**Comment by gretel** [comment]
all libraries added as submodules. `git submodule update` should do the trick. did quite some testing - please let me know if you run into any more issues.
